# Generated by Django 5.2 on 2026-03-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='target_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='app.branch'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sales'), ('PURCHASE', 'Purchase'), ('EXPENSE', 'Expense'), ('CASHBALANCE', 'Cash Balance'), ('TRANSFER', 'Transfer')], max_length=12),
        ),
    ]
