# Generated by Django 5.2 on 2026-03-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_target_branch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashBalanceCategory',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
        migrations.DeleteModel(
            name='PurchaseCategory',
        ),
        migrations.DeleteModel(
            name='SalesCategory',
        ),
    ]
