# Generated by Django 5.2.9 on 2025-12-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_timestamp_transaction_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sales',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sales'), ('EXPENSE', 'Expense'), ('PURCHASE', 'Purchase')], default='Sales', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(default='sdvwrcw'),
            preserve_default=False,
        ),
    ]
