# Generated by Django 5.2.9 on 2025-12-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_expensecategory_purchasecategory_salescategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('RENT', 'Rent'), ('SALARY', 'Salary'), ('UTILITY', 'Utility'), ('MARKETING', 'Marketing'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purchase_category',
            field=models.CharField(blank=True, choices=[('RAW', 'Raw Material'), ('ASSET', 'Asset Purchase'), ('INVENTORY', 'Inventory'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sales_category',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Online Sales'), ('OFFLINE', 'Offline Sales'), ('WHOLESALE', 'Wholesale'), ('OTHER', 'Other')], max_length=30, null=True),
        ),
    ]
